data:
  filepath: "../training/v5/conditionsupdate_apr25.h5"
  output: "output_full_10_21"
  standardize: false
  min_max: true
  n_train_sample: 50000
  n_test_sample: 10000

training:
  batch_size: 256
  es_patience: 5000
  n_epochs: 2
  optimizer: "AdamW"
  learning_rate: 5e-3
  lr_scheduler: "ReduceLROnPlateau"
  lr_scheduler_args:
    mode: "min"
    factor: 0.8
    patience: 20
    threshold: 0.001
    cooldown: 10
    threshold_mode: "rel"
    min_lr: 0
    
wnae:
  sampling: "pcd"
  x_step: 10
  x_step_size: null
  x_noise_std: 0.22
  x_temperature: 0.063
  x_bound: [-3, 3]
  x_clip_grad: null
  x_reject_boundary: false
  x_mh: false
  z_step: 10
  z_step_size: 1
  z_temperature: 0.063
  z_noise_std: 1
  z_bound: null
  z_clip_grad: null
  z_reject_boundary: false
  z_mh: false
  spherical: false
  initial_dist: "gaussian"
  replay: true
  replay_ratio: 0.95
  buffer_size: 10000

model:
  encoder:
    intermediate_architecture: [28, 15]
    bottleneck_size: 8
    drop_out: null
  decoder:
    intermediate_architecture: [57, 128, 64, 32, 24]
    bottleneck_size: 8
    drop_out: null

plot:
  interval: 25


